[package]
name = "aoc2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ex = "0.1"
md5 = "0.7"
itertools = "0.10"
serde = "1.0"
serde_json = "1.0"
derive_more = "0.99"
